<a href="https://colab.research.google.com/github/u1331486/IS-4487-Labs/blob/main/lab3_retailer_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IS 4487 Lab 3

## Outline

Repeat exercises from Lab 2, but with the *SuperStore Retail Orders* dataset
- Loading installed packages
- Inspect data
- Explore plot types

<a href="https://colab.research.google.com/github/Stan-Pugsley/is_4487_base/blob/main/Labs/Scripts/lab3_retailer_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Load Libraries

➡️ Assignment Tasks
- Load any necessary libraries

In [156]:

import pandas as pd
import matplotlib as mpl
import sklearn as sl

## Import Data into Dataframe

➡️ Assignment Tasks
- Import data from the SuperStore retail dataset into a dataframe (in GitHub go to Labs > DataSets)
- Describe or profile the dataframe

In [157]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

df = pd.read_csv (r'/content/gdrive/MyDrive/Colab Notebooks/superstore_retail_orders.csv')

print (df)

Mounted at /content/gdrive
      customer_id      customer_name          address_line_1          city  \
0              67      Gordy Matteau     59 Northland Circle    Wilmington
1             201     Cort Paskerful         769 Buell Drive    Huntsville
2              45    Willetta Lumley       41 Ridgeway Alley        Irvine
3             106   Alison Batterton           489 Erie Hill      Richmond
4             357  Martelle Paxeford    451 Manitowish Place      Richmond
...           ...                ...                     ...           ...
9564          637  Jayson Andriessen  0819 Crownhardt Circle     Allentown
9565          370    Darby Tesseyman     7468 Jackson Circle        Albany
9566          598   Henka De Ferrari      89 Sunnyside Drive  Redwood City
9567          737    Tommie Penvarne    9630 Washington Hill     Watertown
9568          482       Matelda Bull      6406 Bultman Alley  Gaithersburg

      state_province  postal_code  order_id  order_date  customer_id.1  \
0                DE       19805.0      1001  2020-01-11             67
1                AL       35810.0      1002  2019-11-22            201
2                CA       92612.0      1003  2019-09-17             45
3                VA       23293.0      1004  2019-12-09            106
4                VA       23293.0      1005  2019-06-08            357
...              ...          ...       ...         ...            ...
9564  Pennsylvania            NaN      8143  2021-06-13            637
9565             NY       12210.0      8144  2021-06-16            370
9566     California       94064.0      8145  2021-05-09            598
9567  Massachusetts        2472.0      8146  2021-04-13            737
9568       Maryland       20883.0      8147  2021-03-21            482

      order_id.1  product_id  quantity  product_id.1            product_name  \
0           1001         106       3.0           106       Great value Juice
1           1002         104       2.0           104                    Desk
2           1003         107       5.0           107          Dove deodorant
3           1004         106       8.0           106       Great value Juice
4           1005         107       7.0           107          Dove deodorant
...          ...         ...       ...           ...                     ...
9564        8143         113      16.0           113          Extension cord
9565        8144         109       1.0           109  Samsung Galaxy Note 10
9566        8145         110       1.0           110         Apple iPad Mini
9567        8146         113       2.0           113          Extension cord
9568        8147         113       5.0           113          Extension cord

     product_price total_amount order_year_month order_month
0            $1.99        $5.97          2020-01    January
1           $85.98      $171.96          2019-11   November
2            $3.99       $19.95          2019-09   September
3            $1.99       $15.92          2019-12   December
4            $3.99       $27.93          2019-06       June
...            ...          ...              ...         ...
9564        $15.59      $249.44          2021-06       June
9565       $749.99      $749.99          2021-06       June
9566       $329.99      $329.99          2021-05        May
9567        $15.59       $31.18          2021-04      April
9568        $15.59       $77.95          2021-03      March

[9569 rows x 18 columns]

In [158]:
df.describe()

,customer_id,postal_code,order_id,customer_id.1,order_id.1,product_id,quantity,product_id.1
count,9569.000000,9416.000000,9569.000000,9569.000000,9569.000000,9569.000000,9513.000000,9569.000000
mean,282.910962,52225.007116,5107.539450,282.910962,5107.539450,106.736650,3.453380,106.736650
std,199.763947,29619.544418,2043.449403,199.763947,2043.449403,3.694805,4.393894,3.694805
min,1.000000,1105.000000,1001.000000,1.000000,1001.000000,101.000000,1.000000,101.000000
25%,127.000000,27409.000000,3393.000000,127.000000,3393.000000,104.000000,1.000000,104.000000
50%,253.000000,48295.000000,5577.000000,253.000000,5577.000000,107.000000,1.000000,107.000000
75%,376.000000,79923.000000,6829.000000,376.000000,6829.000000,110.000000,4.000000,110.000000
max,800.000000,99812.000000,8147.000000,800.000000,8147.000000,114.000000,20.000000,114.000000

In [159]:
df.head(10)

,customer_id,customer_name,address_line_1,city,state_province,postal_code,order_id,order_date,customer_id.1,order_id.1,product_id,quantity,product_id.1,product_name,product_price,total_amount,order_year_month,order_month
0,67,Gordy Matteau,59 Northland Circle,Wilmington,DE,19805.0,1001,2020-01-11,67,1001,106,3.0,106,Great value Juice,$1.99,$5.97,2020-01,January
1,201,Cort Paskerful,769 Buell Drive,Huntsville,AL,35810.0,1002,2019-11-22,201,1002,104,2.0,104,Desk,$85.98,$171.96,2019-11,November
2,45,Willetta Lumley,41 Ridgeway Alley,Irvine,CA,92612.0,1003,2019-09-17,45,1003,107,5.0,107,Dove deodorant,$3.99,$19.95,2019-09,September
3,106,Alison Batterton,489 Erie Hill,Richmond,VA,23293.0,1004,2019-12-09,106,1004,106,8.0,106,Great value Juice,$1.99,$15.92,2019-12,December
4,357,Martelle Paxeford,451 Manitowish Place,Richmond,VA,23293.0,1005,2019-06-08,357,1005,107,7.0,107,Dove deodorant,$3.99,$27.93,2019-06,June
5,351,Glenn Reville,3 Springview Drive,Dallas,TX,75277.0,1006,2020-02-18,351,1006,106,4.0,106,Great value Juice,$1.99,$7.96,2020-02,February
6,233,Cosette Berkowitz,7619 Susan Lane,South Bend,IN,46634.0,1007,2019-10-25,233,1007,105,2.0,105,Office Chair,$55.99,$111.98,2019-10,October
7,121,Nisse Cunniam,0 Dennis Pass,Lincoln,NE,68531.0,1008,2019-11-10,121,1008,101,1.0,101,Dell E5470 Laptop,$485.00,$485.00,2019-11,November
8,232,Yank Eayrs,8176 Lawn Drive,Washington,DC,20575.0,1009,2019-09-27,232,1009,110,1.0,110,Apple iPad Mini,$329.99,$329.99,2019-09,September
9,113,Jamesy Brothwood,0693 Evergreen Pass,Scranton,PA,18514.0,1010,2019-09-02,113,1010,108,1.0,108,Printer,$59.99,$59.99,2019-09,September

In [160]:
df.tail(10)

,customer_id,customer_name,address_line_1,city,state_province,postal_code,order_id,order_date,customer_id.1,order_id.1,product_id,quantity,product_id.1,product_name,product_price,total_amount,order_year_month,order_month
9559,311,Ardella Lynagh,5092 Summer Ridge Court,Tulsa,OK,74116.0,8138,2021-07-15,311,8138,114,3.0,114,"Black Pens, 12-pack",$4.99,$14.97,2021-07,July
9560,30,Mano Swanborrow,1845 Waywood Alley,Saint Petersburg,FL,33737.0,8139,2021-03-25,30,8139,109,1.0,109,Samsung Galaxy Note 10,$749.99,$749.99,2021-03,March
9561,240,Barnard Hatley,5541 Kim Alley,Duluth,GA,30195.0,8140,2021-03-04,240,8140,110,1.0,110,Apple iPad Mini,$329.99,$329.99,2021-03,March
9562,782,Edmund Hugues,814 Scott Terrace,Kansas City,Missouri,64136.0,8141,2021-01-20,782,8141,110,NaN,110,Apple iPad Mini,$329.99,NaN,2021-01,January
9563,722,Marwin Darrigoe,22 South Crossing,Houston,Texas,NaN,8142,2021-08-26,722,8142,109,1.0,109,Samsung Galaxy Note 10,$749.99,$749.99,2021-08,August
9564,637,Jayson Andriessen,0819 Crownhardt Circle,Allentown,Pennsylvania,NaN,8143,2021-06-13,637,8143,113,16.0,113,Extension cord,$15.59,$249.44,2021-06,June
9565,370,Darby Tesseyman,7468 Jackson Circle,Albany,NY,12210.0,8144,2021-06-16,370,8144,109,1.0,109,Samsung Galaxy Note 10,$749.99,$749.99,2021-06,June
9566,598,Henka De Ferrari,89 Sunnyside Drive,Redwood City,California,94064.0,8145,2021-05-09,598,8145,110,1.0,110,Apple iPad Mini,$329.99,$329.99,2021-05,May
9567,737,Tommie Penvarne,9630 Washington Hill,Watertown,Massachusetts,2472.0,8146,2021-04-13,737,8146,113,2.0,113,Extension cord,$15.59,$31.18,2021-04,April
9568,482,Matelda Bull,6406 Bultman Alley,Gaithersburg,Maryland,20883.0,8147,2021-03-21,482,8147,113,5.0,113,Extension cord,$15.59,$77.95,2021-03,March

## Prepare Data

➡️ Assignment Tasks
- Convert the Total_Amount into a number (not a string)
- Remove rows with empty (NULL) values
- Optional: Locate outliers in any of the variables.   Filter them out if they are mistakes; keep them if they are exceptional cases.

In [161]:
df['total_amount'] = df['total_amount'].astype(str).str.replace('$','')
df['total_amount'] = pd.to_numeric(df['total_amount'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9569 entries, 0 to 9568
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       9569 non-null   int64
 1   customer_name     9569 non-null   object
 2   address_line_1    9448 non-null   object
 3   city              9516 non-null   object
 4   state_province    9569 non-null   object
 5   postal_code       9416 non-null   float64
 6   order_id          9569 non-null   int64
 7   order_date        9312 non-null   object
 8   customer_id.1     9569 non-null   int64
 9   order_id.1        9569 non-null   int64
 10  product_id        9569 non-null   int64
 11  quantity          9513 non-null   float64
 12  product_id.1      9569 non-null   int64
 13  product_name      9569 non-null   object
 14  product_price     9569 non-null   object
 15  total_amount      9296 non-null   float64
 16  order_year_month  9312 non-null   object
 17  order_month       9312 non-null   object
dtypes: float64(3), int64(6), object(9)
memory usage: 1.3+ MB

<ipython-input-161-e32911d286bb>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['total_amount'] = df['total_amount'].astype(str).str.replace('$','')

Remove null values with dropna function

In [176]:
df = df.dropna()
print(df.isnull().sum())

customer_id         0
customer_name       0
address_line_1      0
city                0
state_province      0
postal_code         0
order_id            0
order_date          0
customer_id.1       0
order_id.1          0
product_id          0
quantity            0
product_id.1        0
product_name        0
product_price       0
total_amount        0
order_year_month    0
order_month         0
dtype: int64

In [177]:
df.head(10)

,customer_id,customer_name,address_line_1,city,state_province,postal_code,order_id,order_date,customer_id.1,order_id.1,product_id,quantity,product_id.1,product_name,product_price,total_amount,order_year_month,order_month
0,67,Gordy Matteau,59 Northland Circle,Wilmington,DE,19805.0,1001,2020-01-11,67,1001,106,3.0,106,Great value Juice,$1.99,5.97,2020-01,January
1,201,Cort Paskerful,769 Buell Drive,Huntsville,AL,35810.0,1002,2019-11-22,201,1002,104,2.0,104,Desk,$85.98,171.96,2019-11,November
2,45,Willetta Lumley,41 Ridgeway Alley,Irvine,CA,92612.0,1003,2019-09-17,45,1003,107,5.0,107,Dove deodorant,$3.99,19.95,2019-09,September
3,106,Alison Batterton,489 Erie Hill,Richmond,VA,23293.0,1004,2019-12-09,106,1004,106,8.0,106,Great value Juice,$1.99,15.92,2019-12,December
4,357,Martelle Paxeford,451 Manitowish Place,Richmond,VA,23293.0,1005,2019-06-08,357,1005,107,7.0,107,Dove deodorant,$3.99,27.93,2019-06,June
5,351,Glenn Reville,3 Springview Drive,Dallas,TX,75277.0,1006,2020-02-18,351,1006,106,4.0,106,Great value Juice,$1.99,7.96,2020-02,February
6,233,Cosette Berkowitz,7619 Susan Lane,South Bend,IN,46634.0,1007,2019-10-25,233,1007,105,2.0,105,Office Chair,$55.99,111.98,2019-10,October
7,121,Nisse Cunniam,0 Dennis Pass,Lincoln,NE,68531.0,1008,2019-11-10,121,1008,101,1.0,101,Dell E5470 Laptop,$485.00,485.00,2019-11,November
8,232,Yank Eayrs,8176 Lawn Drive,Washington,DC,20575.0,1009,2019-09-27,232,1009,110,1.0,110,Apple iPad Mini,$329.99,329.99,2019-09,September
9,113,Jamesy Brothwood,0693 Evergreen Pass,Scranton,PA,18514.0,1010,2019-09-02,113,1010,108,1.0,108,Printer,$59.99,59.99,2019-09,September

In [164]:
df.tail(10)

,customer_id,customer_name,address_line_1,city,state_province,postal_code,order_id,order_date,customer_id.1,order_id.1,product_id,quantity,product_id.1,product_name,product_price,total_amount,order_year_month,order_month
9555,721,Antone Winfindine,50 Steensland Junction,Sacramento,California,95833.0,8133,2021-03-10,721,8133,111,5.0,111,Printer Ink Cartridge,$39.99,199.95,2021-03,March
9556,380,Anson Mancer,0 Starling Road,Olympia,WA,98506.0,8135,2021-01-02,380,8135,113,9.0,113,Extension cord,$15.59,140.31,2021-01,January
9557,618,Dionysus Aslum,75873 Towne Plaza,Yonkers,New York,10705.0,8136,2021-07-03,618,8136,114,13.0,114,"Black Pens, 12-pack",$4.99,64.87,2021-07,July
9559,311,Ardella Lynagh,5092 Summer Ridge Court,Tulsa,OK,74116.0,8138,2021-07-15,311,8138,114,3.0,114,"Black Pens, 12-pack",$4.99,14.97,2021-07,July
9560,30,Mano Swanborrow,1845 Waywood Alley,Saint Petersburg,FL,33737.0,8139,2021-03-25,30,8139,109,1.0,109,Samsung Galaxy Note 10,$749.99,749.99,2021-03,March
9561,240,Barnard Hatley,5541 Kim Alley,Duluth,GA,30195.0,8140,2021-03-04,240,8140,110,1.0,110,Apple iPad Mini,$329.99,329.99,2021-03,March
9565,370,Darby Tesseyman,7468 Jackson Circle,Albany,NY,12210.0,8144,2021-06-16,370,8144,109,1.0,109,Samsung Galaxy Note 10,$749.99,749.99,2021-06,June
9566,598,Henka De Ferrari,89 Sunnyside Drive,Redwood City,California,94064.0,8145,2021-05-09,598,8145,110,1.0,110,Apple iPad Mini,$329.99,329.99,2021-05,May
9567,737,Tommie Penvarne,9630 Washington Hill,Watertown,Massachusetts,2472.0,8146,2021-04-13,737,8146,113,2.0,113,Extension cord,$15.59,31.18,2021-04,April
9568,482,Matelda Bull,6406 Bultman Alley,Gaithersburg,Maryland,20883.0,8147,2021-03-21,482,8147,113,5.0,113,Extension cord,$15.59,77.95,2021-03,March

In [165]:
df.describe()

,customer_id,postal_code,order_id,customer_id.1,order_id.1,product_id,quantity,product_id.1,total_amount
count,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000,8768.000000
mean,268.838846,52211.691834,4993.642678,268.838846,4993.642678,106.732208,3.377053,106.732208,313.472843
std,190.387498,29690.256129,2032.525375,190.387498,2032.525375,3.658348,4.290116,3.658348,322.533974
min,1.000000,1105.000000,1001.000000,1.000000,1001.000000,101.000000,1.000000,101.000000,1.990000
25%,121.000000,27404.000000,3272.750000,121.000000,3272.750000,104.000000,1.000000,104.000000,55.990000
50%,243.000000,48295.000000,5450.500000,243.000000,5450.500000,107.000000,1.000000,107.000000,132.515000
75%,363.000000,79923.000000,6689.250000,363.000000,6689.250000,110.000000,4.000000,110.000000,485.000000
max,800.000000,99812.000000,8147.000000,800.000000,8147.000000,114.000000,20.000000,114.000000,988.720000

In [166]:
df = df.dropna()

print(df.dtypes)
print(df.isnull().sum())
print(df.describe())

customer_id           int64
customer_name        object
address_line_1       object
city                 object
state_province       object
postal_code         float64
order_id              int64
order_date           object
customer_id.1         int64
order_id.1            int64
product_id            int64
quantity            float64
product_id.1          int64
product_name         object
product_price        object
total_amount        float64
order_year_month     object
order_month          object
dtype: object
customer_id         0
customer_name       0
address_line_1      0
city                0
state_province      0
postal_code         0
order_id            0
order_date          0
customer_id.1       0
order_id.1          0
product_id          0
quantity            0
product_id.1        0
product_name        0
product_price       0
total_amount        0
order_year_month    0
order_month         0
dtype: int64
       customer_id   postal_code     order_id  customer_id.1   order_id.1  \
count  8768.000000   8768.000000  8768.000000    8768.000000  8768.000000
mean    268.838846  52211.691834  4993.642678     268.838846  4993.642678
std     190.387498  29690.256129  2032.525375     190.387498  2032.525375
min       1.000000   1105.000000  1001.000000       1.000000  1001.000000
25%     121.000000  27404.000000  3272.750000     121.000000  3272.750000
50%     243.000000  48295.000000  5450.500000     243.000000  5450.500000
75%     363.000000  79923.000000  6689.250000     363.000000  6689.250000
max     800.000000  99812.000000  8147.000000     800.000000  8147.000000

        product_id     quantity  product_id.1  total_amount
count  8768.000000  8768.000000   8768.000000   8768.000000
mean    106.732208     3.377053    106.732208    313.472843
std       3.658348     4.290116      3.658348    322.533974
min     101.000000     1.000000    101.000000      1.990000
25%     104.000000     1.000000    104.000000     55.990000
50%     107.000000     1.000000    107.000000    132.515000
75%     110.000000     4.000000    110.000000    485.000000
max     114.000000    20.000000    114.000000    988.720000

In [178]:
from scipy import stats

In [179]:
z_scores = stats.zscore(df['total_amount'])
threshold = 3
df = df[(z_scores < threshold)]

In [180]:
print(df)

      customer_id      customer_name        address_line_1          city  \
0              67      Gordy Matteau   59 Northland Circle    Wilmington
1             201     Cort Paskerful       769 Buell Drive    Huntsville
2              45    Willetta Lumley     41 Ridgeway Alley        Irvine
3             106   Alison Batterton         489 Erie Hill      Richmond
4             357  Martelle Paxeford  451 Manitowish Place      Richmond
...           ...                ...                   ...           ...
9561          240     Barnard Hatley        5541 Kim Alley        Duluth
9565          370    Darby Tesseyman   7468 Jackson Circle        Albany
9566          598   Henka De Ferrari    89 Sunnyside Drive  Redwood City
9567          737    Tommie Penvarne  9630 Washington Hill     Watertown
9568          482       Matelda Bull    6406 Bultman Alley  Gaithersburg

      state_province  postal_code  order_id  order_date  customer_id.1  \
0                DE       19805.0      1001  2020-01-11             67
1                AL       35810.0      1002  2019-11-22            201
2                CA       92612.0      1003  2019-09-17             45
3                VA       23293.0      1004  2019-12-09            106
4                VA       23293.0      1005  2019-06-08            357
...              ...          ...       ...         ...            ...
9561             GA       30195.0      8140  2021-03-04            240
9565             NY       12210.0      8144  2021-06-16            370
9566     California       94064.0      8145  2021-05-09            598
9567  Massachusetts        2472.0      8146  2021-04-13            737
9568       Maryland       20883.0      8147  2021-03-21            482

      order_id.1  product_id  quantity  product_id.1            product_name  \
0           1001         106       3.0           106       Great value Juice
1           1002         104       2.0           104                    Desk
2           1003         107       5.0           107          Dove deodorant
3           1004         106       8.0           106       Great value Juice
4           1005         107       7.0           107          Dove deodorant
...          ...         ...       ...           ...                     ...
9561        8140         110       1.0           110         Apple iPad Mini
9565        8144         109       1.0           109  Samsung Galaxy Note 10
9566        8145         110       1.0           110         Apple iPad Mini
9567        8146         113       2.0           113          Extension cord
9568        8147         113       5.0           113          Extension cord

     product_price  total_amount order_year_month order_month
0            $1.99          5.97          2020-01    January
1           $85.98        171.96          2019-11   November
2            $3.99         19.95          2019-09   September
3            $1.99         15.92          2019-12   December
4            $3.99         27.93          2019-06       June
...            ...           ...              ...         ...
9561       $329.99        329.99          2021-03      March
9565       $749.99        749.99          2021-06       June
9566       $329.99        329.99          2021-05        May
9567        $15.59         31.18          2021-04      April
9568        $15.59         77.95          2021-03      March

[8768 rows x 18 columns]

## Summarize Data

➡️ Assignment Tasks
- Display the average price per month
- Display the total revenue for all months

In [171]:
#average price

**Average price per month**:

In [181]:
average_price_per_month = df.groupby('order_month')['total_amount'].mean()
print(average_price_per_month)

order_month
April        322.324759
August       317.430445
December     308.411832
February     306.211115
January      292.060346
July         293.337456
June         329.207158
March        303.960014
May          311.296518
November     302.205572
October      349.624011
September    323.528796
Name: total_amount, dtype: float64




---



**Average price per month considering both the year and month**:

In [182]:
aaverage_price_per_month = df.groupby('order_year_month')['total_amount'].mean()
print(aaverage_price_per_month)

order_year_month
2019-02    309.599947
2019-03    316.122176
2019-04    327.736575
2019-05    319.580898
2019-06    336.989712
2019-07    292.175024
2019-08    324.951185
2019-09    325.619076
2019-10    357.240905
2019-11    297.083748
2019-12    321.017899
2020-01    291.589188
2020-02    304.212895
2020-03    246.295897
2020-04    300.356582
2020-05    285.122013
2020-06    293.329618
2020-07    309.681228
2020-08    288.717959
2020-09    314.584341
2020-10    310.423276
2020-11    327.773387
2020-12    245.483984
2021-01    293.924786
2021-02    368.730000
2021-03    279.360833
2021-04    332.131429
2021-05    226.770769
2021-06    314.285455
2021-07    197.840000
2021-08    227.448333
Name: total_amount, dtype: float64

In [174]:
#total revenue



---


# **Total Revenue**:

In [175]:
total_revenue = df['total_amount'].sum()
print(f"Total Revenue for All Months: ${total_revenue:.2f}")

Total Revenue for All Months: $2748529.89